services:
  stilguide:
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    ports:
      - '${PORT:-overwrite_dockerfile_expose_port}:${CONTAINER_PORT:-8080}' # Container port must be same as exposed in Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'http', 'localhost:${PORT}']
      interval: 10s
      timeout: 5s
      retries: 12
