module.exports = {
  primitives: {
    gray: {
      lightest: `var(--sk-colors-primitives-gray-lightest)`,
      50: `var(--sk-colors-primitives-gray-50)`,
      100: `var(--sk-colors-primitives-gray-100)`,
      200: `var(--sk-colors-primitives-gray-200)`,
      300: `var(--sk-colors-primitives-gray-300)`,
      400: `var(--sk-colors-primitives-gray-400)`,
      500: `var(--sk-colors-primitives-gray-500)`,
      600: `var(--sk-colors-primitives-gray-600)`,
      700: `var(--sk-colors-primitives-gray-700)`,
      800: `var(--sk-colors-primitives-gray-800)`,
      900: `var(--sk-colors-primitives-gray-900)`,
      darkest: `var(--sk-colors-primitives-gray-darkest)`,
    },

    overlay: {
      darken: {
        1: `var(--sk-colors-primitives-overlay-darken-1)`,
        2: `var(--sk-colors-primitives-overlay-darken-2)`,
        3: `var(--sk-colors-primitives-overlay-darken-3)`,
        4: `var(--sk-colors-primitives-overlay-darken-4)`,
        5: `var(--sk-colors-primitives-overlay-darken-5)`,
        6: `var(--sk-colors-primitives-overlay-darken-6)`,
        7: `var(--sk-colors-primitives-overlay-darken-7)`,
        8: `var(--sk-colors-primitives-overlay-darken-8)`,
        9: `var(--sk-colors-primitives-overlay-darken-9)`,
        10: `var(--sk-colors-primitives-overlay-darken-10)`,
      },
      lighten: {
        1: `var(--sk-colors-primitives-overlay-lighten-1)`,
        2: `var(--sk-colors-primitives-overlay-lighten-2)`,
        3: `var(--sk-colors-primitives-overlay-lighten-3)`,
        4: `var(--sk-colors-primitives-overlay-lighten-4)`,
        5: `var(--sk-colors-primitives-overlay-lighten-5)`,
        6: `var(--sk-colors-primitives-overlay-lighten-6)`,
        7: `var(--sk-colors-primitives-overlay-lighten-7)`,
        8: `var(--sk-colors-primitives-overlay-lighten-8)`,
        9: `var(--sk-colors-primitives-overlay-lighten-9)`,
        10: `var(--sk-colors-primitives-overlay-lighten-10)`,
      },
    },

    //COLORS
    blue: {
      50: `var(--sk-colors-primitives-blue-50)`,
      100: `var(--sk-colors-primitives-blue-100)`,
      200: `var(--sk-colors-primitives-blue-200)`,
      300: `var(--sk-colors-primitives-blue-300)`,
      400: `var(--sk-colors-primitives-blue-400)`,
      500: `var(--sk-colors-primitives-blue-500)`,
      600: `var(--sk-colors-primitives-blue-600)`,
      700: `var(--sk-colors-primitives-blue-700)`,
      800: `var(--sk-colors-primitives-blue-800)`,
      900: `var(--sk-colors-primitives-blue-900)`,
    },
    green: {
      50: `var(--sk-colors-primitives-green-50)`,
      100: `var(--sk-colors-primitives-green-100)`,
      200: `var(--sk-colors-primitives-green-200)`,
      300: `var(--sk-colors-primitives-green-300)`,
      400: `var(--sk-colors-primitives-green-400)`,
      500: `var(--sk-colors-primitives-green-500)`,
      600: `var(--sk-colors-primitives-green-600)`,
      700: `var(--sk-colors-primitives-green-700)`,
      800: `var(--sk-colors-primitives-green-800)`,
      900: `var(--sk-colors-primitives-green-900)`,
    },
    purple: {
      50: `var(--sk-colors-primitives-purple-50)`,
      100: `var(--sk-colors-primitives-purple-100)`,
      200: `var(--sk-colors-primitives-purple-200)`,
      300: `var(--sk-colors-primitives-purple-300)`,
      400: `var(--sk-colors-primitives-purple-400)`,
      500: `var(--sk-colors-primitives-purple-500)`,
      600: `var(--sk-colors-primitives-purple-600)`,
      700: `var(--sk-colors-primitives-purple-700)`,
      800: `var(--sk-colors-primitives-purple-800)`,
      900: `var(--sk-colors-primitives-purple-900)`,
    },
    pink: {
      50: `var(--sk-colors-primitives-pink-50)`,
      100: `var(--sk-colors-primitives-pink-100)`,
      200: `var(--sk-colors-primitives-pink-200)`,
      300: `var(--sk-colors-primitives-pink-300)`,
      400: `var(--sk-colors-primitives-pink-400)`,
      500: `var(--sk-colors-primitives-pink-500)`,
      600: `var(--sk-colors-primitives-pink-600)`,
      700: `var(--sk-colors-primitives-pink-700)`,
      800: `var(--sk-colors-primitives-pink-800)`,
      900: `var(--sk-colors-primitives-pink-900)`,
    },
    orange: {
      50: `var(--sk-colors-primitives-orange-50)`,
      100: `var(--sk-colors-primitives-orange-100)`,
      200: `var(--sk-colors-primitives-orange-200)`,
      300: `var(--sk-colors-primitives-orange-300)`,
      400: `var(--sk-colors-primitives-orange-400)`,
      500: `var(--sk-colors-primitives-orange-500)`,
      600: `var(--sk-colors-primitives-orange-600)`,
      700: `var(--sk-colors-primitives-orange-700)`,
      800: `var(--sk-colors-primitives-orange-800)`,
      900: `var(--sk-colors-primitives-orange-900)`,
    },
    red: {
      50: `var(--sk-colors-primitives-red-50)`,
      100: `var(--sk-colors-primitives-red-100)`,
      200: `var(--sk-colors-primitives-red-200)`,
      300: `var(--sk-colors-primitives-red-300)`,
      400: `var(--sk-colors-primitives-red-400)`,
      500: `var(--sk-colors-primitives-red-500)`,
      600: `var(--sk-colors-primitives-red-600)`,
      700: `var(--sk-colors-primitives-red-700)`,
      800: `var(--sk-colors-primitives-red-800)`,
      900: `var(--sk-colors-primitives-red-900)`,
    },
  },
  body: { DEFAULT: `var(--sk-colors-body-DEFAULT)` },
  black: `var(--sk-colors-black)`,
  white: `var(--sk-colors-white)`,
  primary: {
    DEFAULT: `var(--sk-colors-primary-DEFAULT)`,
    surface: {
      DEFAULT: `var(--sk-colors-primary-surface-DEFAULT)`,
      hover: `var(--sk-colors-primary-surface-hover)`,
      disabled: `var(--sk-colors-primary-surface-disabled)`,
    },
    lightest: `var(--sk-colors-primary-lightest)`,
    50: `var(--sk-colors-primary-50)`,
    100: `var(--sk-colors-primary-100)`,
    200: `var(--sk-colors-primary-200)`,
    300: `var(--sk-colors-primary-300)`,
    400: `var(--sk-colors-primary-400)`,
    500: `var(--sk-colors-primary-500)`,
    600: `var(--sk-colors-primary-600)`,
    700: `var(--sk-colors-primary-700)`,
    800: `var(--sk-colors-primary-800)`,
    900: `var(--sk-colors-primary-900)`,
    darkest: `var(--sk-colors-primary-darkest)`,
  },
  secondary: {
    DEFAULT: `var(--sk-colors-secondary-DEFAULT)`,
    outline: {
      DEFAULT: `var(--sk-colors-secondary-outline-DEFAULT)`,
      hover: `var(--sk-colors-secondary-outline-hover)`,
    },
    surface: {
      DEFAULT: `var(--sk-colors-secondary-surface-DEFAULT)`,
      hover: `var(--sk-colors-secondary-surface-hover)`,
      disabled: `var(--sk-colors-secondary-surface-disabled)`,
    },
    lightest: `var(--sk-colors-secondary-lightest)`,
    50: `var(--sk-colors-secondary-50)`,
    100: `var(--sk-colors-secondary-100)`,
    200: `var(--sk-colors-secondary-200)`,
    300: `var(--sk-colors-secondary-300)`,
    400: `var(--sk-colors-secondary-400)`,
    500: `var(--sk-colors-secondary-500)`,
    600: `var(--sk-colors-secondary-600)`,
    700: `var(--sk-colors-secondary-700)`,
    800: `var(--sk-colors-secondary-800)`,
    900: `var(--sk-colors-secondary-900)`,
    darkest: `var(--sk-colors-secondary-darkest)`,
  },
  tertiary: {
    surface: {
      DEFAULT: `var(--sk-colors-tertiary-surface-DEFAULT)`,
      hover: `var(--sk-colors-tertiary-surface-hover)`,
      disabled: `var(--sk-colors-tertiary-surface-disabled)`,
    },
  },
  dark: {
    DEFAULT: `var(--sk-colors-dark-DEFAULT)`,
    primary: `var(--sk-colors-dark-primary)`,
    secondary: `var(--sk-colors-dark-secondary)`,
    disabled: `var(--sk-colors-dark-disabled)`,
    placeholder: `var(--sk-colors-dark-placeholder)`,
    ghost: `var(--sk-colors-dark-ghost)`,
  },
  light: {
    DEFAULT: `var(--sk-colors-light-DEFAULT)`,
    primary: `var(--sk-colors-light-primary)`,
    secondary: `var(--sk-colors-light-secondary)`,
    disabled: `var(--sk-colors-light-disabled)`,
    placeholder: `var(--sk-colors-light-placeholder)`,
    ghost: `var(--sk-colors-light-ghost)`,
  },
  divider: `var(--sk-colors-divider)`,
  background: {
    DEFAULT: `var(--sk-colors-backgrouhnd-DEFUALT)`,
    content: `var(--sk-colors-background-content)`,
    100: `var(--sk-colors-background-100)`,
    200: `var(--sk-colors-background-200)`,
    'color-mixin': {
      1: `var(--sk-colors-background-color-mixin-1)`,
      2: `var(--sk-colors-background-color-mixin-2)`,
    },
  },
  vattjom: {
    background: {
      100: `var(--sk-colors-vattjom-background-100)`,
      200: `var(--sk-colors-vattjom-background-200)`,
      300: `var(--sk-colors-vattjom-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-vattjom-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-vattjom-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-vattjom-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-vattjom-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-vattjom-text-DEFAULT)`,
      primary: `var(--sk-colors-vattjom-text-primary)`,
      secondary: `var(--sk-colors-vattjom-text-secondary)`,
    },
  },
  gronsta: {
    background: {
      100: `var(--sk-colors-gronsta-background-100)`,
      200: `var(--sk-colors-gronsta-background-200)`,
      300: `var(--sk-colors-gronsta-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-gronsta-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-gronsta-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-gronsta-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-gronsta-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-gronsta-text-DEFAULT)`,
      primary: `var(--sk-colors-gronsta-text-primary)`,
      secondary: `var(--sk-colors-gronsta-text-secondary)`,
    },
  },
  juniskar: {
    background: {
      100: `var(--sk-colors-juniskar-background-100)`,
      200: `var(--sk-colors-juniskar-background-200)`,
      300: `var(--sk-colors-juniskar-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-juniskar-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-juniskar-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-juniskar-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-juniskar-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-juniskar-text-DEFAULT)`,
      primary: `var(--sk-colors-juniskar-text-primary)`,
      secondary: `var(--sk-colors-juniskar-text-secondary)`,
    },
  },
  bjornstigen: {
    background: {
      100: `var(--sk-colors-bjornstigen-background-100)`,
      200: `var(--sk-colors-bjornstigen-background-200)`,
      300: `var(--sk-colors-bjornstigen-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-bjornstigen-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-bjornstigen-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-bjornstigen-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-bjornstigen-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-bjornstigen-text-DEFAULT)`,
      primary: `var(--sk-colors-bjornstigen-text-primary)`,
      secondary: `var(--sk-colors-bjornstigen-text-secondary)`,
    },
  },
  error: {
    DEFAULT: `var(--sk-colors-error-DEFAULT)`,
    background: {
      100: `var(--sk-colors-error-background-100)`,
      200: `var(--sk-colors-error-background-200)`,
      300: `var(--sk-colors-error-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-error-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-error-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-error-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-error-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-error-text-DEFAULT)`,
      primary: `var(--sk-colors-error-text-primary)`,
      secondary: `var(--sk-colors-error-text-secondary)`,
    },
  },
  warning: {
    DEFAULT: `var(--sk-colors-warning-DEFAULT)`,
    background: {
      100: `var(--sk-colors-warning-background-100)`,
      200: `var(--sk-colors-warning-background-200)`,
      300: `var(--sk-colors-warning-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-warning-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-warning-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-warning-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-warning-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-warning-text-DEFAULT)`,
      primary: `var(--sk-colors-warning-text-primary)`,
      secondary: `var(--sk-colors-warning-text-secondary)`,
    },
  },
  info: {
    DEFAULT: `var(--sk-colors-info-DEFAULT)`,
    background: {
      100: `var(--sk-colors-info-background-100)`,
      200: `var(--sk-colors-info-background-200)`,
      300: `var(--sk-colors-info-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-info-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-info-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-info-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-info-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-info-text-DEFAULT)`,
      primary: `var(--sk-colors-info-text-primary)`,
      secondary: `var(--sk-colors-info-text-secondary)`,
    },
  },
  success: {
    DEFAULT: `var(--sk-colors-success-DEFAULT)`,
    background: {
      100: `var(--sk-colors-success-background-100)`,
      200: `var(--sk-colors-success-background-200)`,
      300: `var(--sk-colors-success-background-300)`,
    },
    surface: {
      primary: {
        DEFAULT: `var(--sk-colors-success-surface-primary-DEFAULT)`,
        hover: `var(--sk-colors-success-surface-primary-hover)`,
      },
      accent: {
        DEFAULT: `var(--sk-colors-success-surface-accent-DEFAULT)`,
        hover: `var(--sk-colors-success-surface-accent-hover)`,
      },
    },
    text: {
      DEFAULT: `var(--sk-colors-success-text-DEFAULT)`,
      primary: `var(--sk-colors-success-text-primary)`,
      secondary: `var(--sk-colors-success-text-secondary)`,
    },
  },
};

// primary: {
//   DEFAULT: '--vc-colors-primary-DEFAULT',
//   dark: '--vc-colors-primary-dark',
//   light: '--vc-colors-primary-light',
//   active: '--vc-colors-primary-active',
//   50: '--vc-colors-primary-DEFAULT',
//   100: '--vc-colors-primary-DEFAULT',
//   200: '--vc-colors-primary-DEFAULT',
//   300: '--vc-colors-primary-DEFAULT',
//   400: '--vc-colors-primary-DEFAULT',
//   500: '--vc-colors-primary-DEFAULT',
//   600: '--vc-colors-primary-DEFAULT',
//   700: '--vc-colors-primary-DEFAULT',
//   800: '--vc-colors-primary-DEFAULT',
//   900: '--vc-colors-primary-DEFAULT',
// },

// secondary: {
//   DEFAULT: '--vc-colors-secondary-DEFAULT',
//   dark: '--vc-colors-secondary-dark',
//   light: '--vc-colors-secondary-light',
//   active: '--vc-colors-secondary-active',
//   50: '--vc-colors-secondary-DEFAULT',
//   100: '--vc-colors-secondary-DEFAULT',
//   200: '--vc-colors-secondary-DEFAULT',
//   300: '--vc-colors-secondary-DEFAULT',
//   400: '--vc-colors-secondary-DEFAULT',
//   500: '--vc-colors-secondary-DEFAULT',
//   600: '--vc-colors-secondary-DEFAULT',
//   700: '--vc-colors-secondary-DEFAULT',
//   800: '--vc-colors-secondary-DEFAULT',
//   900: '--vc-colors-secondary-DEFAULT',
// },

// success: {
//   DEFAULT: '--vc-colors-success-DEFAULT',
//   dark: '--vc-colors-success-dark',
//   light: '--vc-colors-success-light',
//   active: '--vc-colors-success-active',
//   50: '--vc-colors-success-DEFAULT',
//   100: '--vc-colors-success-DEFAULT',
//   200: '--vc-colors-success-DEFAULT',
//   300: '--vc-colors-success-DEFAULT',
//   400: '--vc-colors-success-DEFAULT',
//   500: '--vc-colors-success-DEFAULT',
//   600: '--vc-colors-success-DEFAULT',
//   700: '--vc-colors-success-DEFAULT',
//   800: '--vc-colors-success-DEFAULT',
//   900: '--vc-colors-success-DEFAULT',
// },

// info: {
//   DEFAULT: '--vc-colors-info-DEFAULT',
//   dark: '--vc-colors-info-dark',
//   light: '--vc-colors-info-light',
//   active: '--vc-colors-info-active',
//   50: '--vc-colors-info-DEFAULT',
//   100: '--vc-colors-info-DEFAULT',
//   200: '--vc-colors-info-DEFAULT',
//   300: '--vc-colors-info-DEFAULT',
//   400: '--vc-colors-info-DEFAULT',
//   500: '--vc-colors-info-DEFAULT',
//   600: '--vc-colors-info-DEFAULT',
//   700: '--vc-colors-info-DEFAULT',
//   800: '--vc-colors-info-DEFAULT',
//   900: '--vc-colors-info-DEFAULT',
// },

// warning: {
//   DEFAULT: '--vc-colors-warning-DEFAULT',
//   dark: '--vc-colors-warning-dark',
//   light: '--vc-colors-warning-light',
//   active: '--vc-colors-warning-active',
//   50: '--vc-colors-warning-DEFAULT',
//   100: '--vc-colors-warning-DEFAULT',
//   200: '--vc-colors-warning-DEFAULT',
//   300: '--vc-colors-warning-DEFAULT',
//   400: '--vc-colors-warning-DEFAULT',
//   500: '--vc-colors-warning-DEFAULT',
//   600: '--vc-colors-warning-DEFAULT',
//   700: '--vc-colors-warning-DEFAULT',
//   800: '--vc-colors-warning-DEFAULT',
//   900: '--vc-colors-warning-DEFAULT',
// },

// error: {
//   DEFAULT: '--vc-colors-error-DEFAULT',
//   dark: '--vc-colors-error-dark',
//   light: '--vc-colors-error-light',
//   active: '--vc-colors-error-active',
//   50: '--vc-colors-error-DEFAULT',
//   100: '--vc-colors-error-DEFAULT',
//   200: '--vc-colors-error-DEFAULT',
//   300: '--vc-colors-error-DEFAULT',
//   400: '--vc-colors-error-DEFAULT',
//   500: '--vc-colors-error-DEFAULT',
//   600: '--vc-colors-error-DEFAULT',
//   700: '--vc-colors-error-DEFAULT',
//   800: '--vc-colors-error-DEFAULT',
//   900: '--vc-colors-error-DEFAULT',
// },

// neutral: {
//   DEFAULT: '--vc-colors-neutral',
//   50: '--vc-colors-neutral-50',
//   100: '--vc-colors-neutral-100',
//   200: '--vc-colors-neutral-200',
//   300: '--vc-colors-neutral-300',
//   400: '--vc-colors-neutral-400',
//   500: '--vc-colors-neutral-500',
//   600: '--vc-colors-neutral-600',
//   700: '--vc-colors-neutral-700',
//   800: '--vc-colors-neutral-800',
//   900: '--vc-colors-neutral-900',
// },

// whiteAlpha: {
//   50: 'rgba(255, 255, 255, 0.04)',
//   100: 'rgba(255, 255, 255, 0.06)',
//   200: 'rgba(255, 255, 255, 0.08)',
//   300: 'rgba(255, 255, 255, 0.16)',
//   400: 'rgba(255, 255, 255, 0.24)',
//   500: 'rgba(255, 255, 255, 0.36)',
//   600: 'rgba(255, 255, 255, 0.48)',
//   700: 'rgba(255, 255, 255, 0.64)',
//   800: 'rgba(255, 255, 255, 0.80)',
//   900: 'rgba(255, 255, 255, 0.92)',
// },

// blackAlpha: {
//   50: 'rgba(0, 0, 0, 0.04)',
//   100: 'rgba(0, 0, 0, 0.06)',
//   200: 'rgba(0, 0, 0, 0.08)',
//   300: 'rgba(0, 0, 0, 0.16)',
//   400: 'rgba(0, 0, 0, 0.24)',
//   500: 'rgba(0, 0, 0, 0.36)',
//   600: 'rgba(0, 0, 0, 0.48)',
//   700: 'rgba(0, 0, 0, 0.64)',
//   800: 'rgba(0, 0, 0, 0.80)',
//   900: 'rgba(0, 0, 0, 0.92)',
// }
