const withOpacity = require('./with-opacity');

module.exports = {
  primary: {
    DEFAULT: withOpacity('--vc-colors-primary-DEFAULT'),
    dark: withOpacity('--vc-colors-primary-dark'),
    light: withOpacity('--vc-colors-primary-light'),
    active: withOpacity('--vc-colors-primary-active'),
    50: withOpacity('--vc-colors-primary-DEFAULT'),
    100: withOpacity('--vc-colors-primary-DEFAULT'),
    200: withOpacity('--vc-colors-primary-DEFAULT'),
    300: withOpacity('--vc-colors-primary-DEFAULT'),
    400: withOpacity('--vc-colors-primary-DEFAULT'),
    500: withOpacity('--vc-colors-primary-DEFAULT'),
    600: withOpacity('--vc-colors-primary-DEFAULT'),
    700: withOpacity('--vc-colors-primary-DEFAULT'),
    800: withOpacity('--vc-colors-primary-DEFAULT'),
    900: withOpacity('--vc-colors-primary-DEFAULT'),
  },

  secondary: {
    DEFAULT: withOpacity('--vc-colors-secondary-DEFAULT'),
    dark: withOpacity('--vc-colors-secondary-dark'),
    light: withOpacity('--vc-colors-secondary-light'),
    active: withOpacity('--vc-colors-secondary-active'),
    50: withOpacity('--vc-colors-secondary-DEFAULT'),
    100: withOpacity('--vc-colors-secondary-DEFAULT'),
    200: withOpacity('--vc-colors-secondary-DEFAULT'),
    300: withOpacity('--vc-colors-secondary-DEFAULT'),
    400: withOpacity('--vc-colors-secondary-DEFAULT'),
    500: withOpacity('--vc-colors-secondary-DEFAULT'),
    600: withOpacity('--vc-colors-secondary-DEFAULT'),
    700: withOpacity('--vc-colors-secondary-DEFAULT'),
    800: withOpacity('--vc-colors-secondary-DEFAULT'),
    900: withOpacity('--vc-colors-secondary-DEFAULT'),
  },

  success: {
    DEFAULT: withOpacity('--vc-colors-success-DEFAULT'),
    dark: withOpacity('--vc-colors-success-dark'),
    light: withOpacity('--vc-colors-success-light'),
    active: withOpacity('--vc-colors-success-active'),
    50: withOpacity('--vc-colors-success-DEFAULT'),
    100: withOpacity('--vc-colors-success-DEFAULT'),
    200: withOpacity('--vc-colors-success-DEFAULT'),
    300: withOpacity('--vc-colors-success-DEFAULT'),
    400: withOpacity('--vc-colors-success-DEFAULT'),
    500: withOpacity('--vc-colors-success-DEFAULT'),
    600: withOpacity('--vc-colors-success-DEFAULT'),
    700: withOpacity('--vc-colors-success-DEFAULT'),
    800: withOpacity('--vc-colors-success-DEFAULT'),
    900: withOpacity('--vc-colors-success-DEFAULT'),
  },

  info: {
    DEFAULT: withOpacity('--vc-colors-info-DEFAULT'),
    dark: withOpacity('--vc-colors-info-dark'),
    light: withOpacity('--vc-colors-info-light'),
    active: withOpacity('--vc-colors-info-active'),
    50: withOpacity('--vc-colors-info-DEFAULT'),
    100: withOpacity('--vc-colors-info-DEFAULT'),
    200: withOpacity('--vc-colors-info-DEFAULT'),
    300: withOpacity('--vc-colors-info-DEFAULT'),
    400: withOpacity('--vc-colors-info-DEFAULT'),
    500: withOpacity('--vc-colors-info-DEFAULT'),
    600: withOpacity('--vc-colors-info-DEFAULT'),
    700: withOpacity('--vc-colors-info-DEFAULT'),
    800: withOpacity('--vc-colors-info-DEFAULT'),
    900: withOpacity('--vc-colors-info-DEFAULT'),
  },

  warning: {
    DEFAULT: withOpacity('--vc-colors-warning-DEFAULT'),
    dark: withOpacity('--vc-colors-warning-dark'),
    light: withOpacity('--vc-colors-warning-light'),
    active: withOpacity('--vc-colors-warning-active'),
    50: withOpacity('--vc-colors-warning-DEFAULT'),
    100: withOpacity('--vc-colors-warning-DEFAULT'),
    200: withOpacity('--vc-colors-warning-DEFAULT'),
    300: withOpacity('--vc-colors-warning-DEFAULT'),
    400: withOpacity('--vc-colors-warning-DEFAULT'),
    500: withOpacity('--vc-colors-warning-DEFAULT'),
    600: withOpacity('--vc-colors-warning-DEFAULT'),
    700: withOpacity('--vc-colors-warning-DEFAULT'),
    800: withOpacity('--vc-colors-warning-DEFAULT'),
    900: withOpacity('--vc-colors-warning-DEFAULT'),
  },

  error: {
    DEFAULT: withOpacity('--vc-colors-error-DEFAULT'),
    dark: withOpacity('--vc-colors-error-dark'),
    light: withOpacity('--vc-colors-error-light'),
    active: withOpacity('--vc-colors-error-active'),
    50: withOpacity('--vc-colors-error-DEFAULT'),
    100: withOpacity('--vc-colors-error-DEFAULT'),
    200: withOpacity('--vc-colors-error-DEFAULT'),
    300: withOpacity('--vc-colors-error-DEFAULT'),
    400: withOpacity('--vc-colors-error-DEFAULT'),
    500: withOpacity('--vc-colors-error-DEFAULT'),
    600: withOpacity('--vc-colors-error-DEFAULT'),
    700: withOpacity('--vc-colors-error-DEFAULT'),
    800: withOpacity('--vc-colors-error-DEFAULT'),
    900: withOpacity('--vc-colors-error-DEFAULT'),
  },

  neutral: {
    DEFAULT: withOpacity('--vc-colors-neutral'),
    50: withOpacity('--vc-colors-neutral-50'),
    100: withOpacity('--vc-colors-neutral-100'),
    200: withOpacity('--vc-colors-neutral-200'),
    300: withOpacity('--vc-colors-neutral-300'),
    400: withOpacity('--vc-colors-neutral-400'),
    500: withOpacity('--vc-colors-neutral-500'),
    600: withOpacity('--vc-colors-neutral-600'),
    700: withOpacity('--vc-colors-neutral-700'),
    800: withOpacity('--vc-colors-neutral-800'),
    900: withOpacity('--vc-colors-neutral-900'),
  },

  whiteAlpha: {
    50: 'rgba(255, 255, 255, 0.04)',
    100: 'rgba(255, 255, 255, 0.06)',
    200: 'rgba(255, 255, 255, 0.08)',
    300: 'rgba(255, 255, 255, 0.16)',
    400: 'rgba(255, 255, 255, 0.24)',
    500: 'rgba(255, 255, 255, 0.36)',
    600: 'rgba(255, 255, 255, 0.48)',
    700: 'rgba(255, 255, 255, 0.64)',
    800: 'rgba(255, 255, 255, 0.80)',
    900: 'rgba(255, 255, 255, 0.92)',
  },

  blackAlpha: {
    50: 'rgba(0, 0, 0, 0.04)',
    100: 'rgba(0, 0, 0, 0.06)',
    200: 'rgba(0, 0, 0, 0.08)',
    300: 'rgba(0, 0, 0, 0.16)',
    400: 'rgba(0, 0, 0, 0.24)',
    500: 'rgba(0, 0, 0, 0.36)',
    600: 'rgba(0, 0, 0, 0.48)',
    700: 'rgba(0, 0, 0, 0.64)',
    800: 'rgba(0, 0, 0, 0.80)',
    900: 'rgba(0, 0, 0, 0.92)',
  },
};
