module.exports = {
  spacing: {
    0: 'var(--sk-spacing-0)',
    2: 'var(--sk-spacing-2)',
    4: 'var(--sk-spacing-4)',
    6: 'var(--sk-spacing-6)',
    8: 'var(--sk-spacing-8)',
    10: 'var(--sk-spacing-10)',
    12: 'var(--sk-spacing-12)',
    14: 'var(--sk-spacing-14)',
    16: 'var(--sk-spacing-16)',
    18: 'var(--sk-spacing-18)',
    20: 'var(--sk-spacing-20)',
    24: 'var(--sk-spacing-24)',
    32: 'var(--sk-spacing-32)',
    40: 'var(--sk-spacing-40)',
    48: 'var(--sk-spacing-48)',
    56: 'var(--sk-spacing-56)',
    64: 'var(--sk-spacing-64)',
    72: 'var(--sk-spacing-72)',
    80: 'var(--sk-spacing-80)',
  },

  fontSizes: {
    'display-1': 'var(--sk-fontSize-display-1-DEFAULT)',
    'display-1-lg': 'var(--sk-fontSize-display-1-lg)',
    'display-1-md': 'var(--sk-fontSize-display-1-md)',
    'display-1-sm': 'var(--sk-fontSize-display-1-sm)',
    'display-2': 'var(--sk-fontSize-display-2-DEFAULT)',
    'display-2-lg': 'var(--sk-fontSize-display-2-lg)',
    'display-2-md': 'var(--sk-fontSize-display-2-md)',
    'display-2-sm': 'var(--sk-fontSize-display-2-sm)',
    'display-3': 'var(--sk-fontSize-display-3-DEFAULT)',
    'display-3-lg': 'var(--sk-fontSize-display-3-lg)',
    'display-3-md': 'var(--sk-fontSize-display-3-md)',
    'display-3-sm': 'var(--sk-fontSize-display-3-sm)',

    h1: 'var(--sk-fontSize-h-1-DEFAULT)',
    'h1-lg': 'var(--sk-fontSize-h-1-lg)',
    'h1-md': 'var(--sk-fontSize-h-1-md)',
    'h1-sm': 'var(--sk-fontSize-h-1-sm)',
    h2: 'var(--sk-fontSize-h-2-DEFAULT)',
    'h2-lg': 'var(--sk-fontSize-h-2-lg)',
    'h2-md': 'var(--sk-fontSize-h-2-md)',
    'h2-sm': 'var(--sk-fontSize-h-2-sm)',
    h3: 'var(--sk-fontSize-h-3-DEFAULT)',
    'h3-lg': 'var(--sk-fontSize-h-3-lg)',
    'h3-md': 'var(--sk-fontSize-h-3-md)',
    'h3-sm': 'var(--sk-fontSize-h-3-sm)',
    h4: 'var(--sk-fontSize-h-4-DEFAULT)',
    'h4-lg': 'var(--sk-fontSize-h-4-lg)',
    'h4-md': 'var(--sk-fontSize-h-4-md)',
    'h4-sm': 'var(--sk-fontSize-h-4-sm)',

    'label-lg': 'var(--sk-fontSize-label-lg)',
    'label-md': 'var(--sk-fontSize-label-md)',
    'label-sm': 'var(--sk-fontSize-label-sm)',

    'input-lg': 'var(--sk-fontSize-input-lg)',
    'input-md': 'var(--sk-fontSize-input-md)',
    'input-sm': 'var(--sk-fontSize-input-sm)',

    lead: 'var(--sk-fontSize-lead)',
    base: 'var(--sk-fontSize-base)',
    lg: 'var(--sk-fontSize-lg)',
    sm: 'var(--sk-fontSize-sm)',
  },
  lineHeights: {
    'display-1': 'var(--sk-lineHeight-display-1-DEFAULT)',
    'display-1-lg': 'var(--sk-lineHeight-display-1-lg)',
    'display-1-md': 'var(--sk-lineHeight-display-1-md)',
    'display-1-sm': 'var(--sk-lineHeight-display-1-sm)',
    'display-2': 'var(--sk-lineHeight-display-2-DEFAULT)',
    'display-2-lg': 'var(--sk-lineHeight-display-2-lg)',
    'display-2-md': 'var(--sk-lineHeight-display-2-md)',
    'display-2-sm': 'var(--sk-lineHeight-display-2-sm)',
    'display-3': 'var(--sk-lineHeight-display-3-DEFAULT)',
    'display-3-lg': 'var(--sk-lineHeight-display-3-lg)',
    'display-3-md': 'var(--sk-lineHeight-display-3-md)',
    'display-3-sm': 'var(--sk-lineHeight-display-3-sm)',

    h1: 'var(--sk-lineHeight-h-1-DEFAULT)',
    'h1-lg': 'var(--sk-lineHeight-h-1-lg)',
    'h1-md': 'var(--sk-lineHeight-h-1-md)',
    'h1-sm': 'var(--sk-lineHeight-h-1-sm)',
    h2: 'var(--sk-lineHeight-h-2-DEFAULT)',
    'h2-lg': 'var(--sk-lineHeight-h-2-lg)',
    'h2-md': 'var(--sk-lineHeight-h-2-md)',
    'h2-sm': 'var(--sk-lineHeight-h-2-sm)',
    h3: 'var(--sk-lineHeight-h-3-DEFAULT)',
    'h3-lg': 'var(--sk-lineHeight-h-3-lg)',
    'h3-md': 'var(--sk-lineHeight-h-3-md)',
    'h3-sm': 'var(--sk-lineHeight-h-3-sm)',
    h4: 'var(--sk-lineHeight-h-4-DEFAULT)',
    'h4-lg': 'var(--sk-lineHeight-h-4-lg)',
    'h4-md': 'var(--sk-lineHeight-h-4-md)',
    'h4-sm': 'var(--sk-lineHeight-h-4-sm)',

    'label-lg': 'var(--sk-lineHeight-label-lg)',
    'label-md': 'var(--sk-lineHeight-label-md)',
    'label-sm': 'var(--sk-lineHeight-label-sm)',

    'input-lg': 'var(--sk-lineHeight-input-lg)',
    'input-md': 'var(--sk-lineHeight-input-md)',
    'input-sm': 'var(--sk-lineHeight-input-sm)',

    lead: 'var(--sk-lineHeight-lead)',
    base: 'var(--sk-lineHeight-base)',
    lg: 'var(--sk-lineHeight-lg)',
    sm: 'var(--sk-lineHeight-sm)',
  },
  radius: {
    DEFAULT: 'var(--sk-radius-utility-DEFAULT)',
    full: 'var(--sk-radius-circular-DEFAULT)',
    none: 'var(--sk-spacing-0)',
    circular: 'var(--sk-radius-circular-DEFAULT)',
    'circular-lg': 'var(--sk-radius-circular-lg)',
    'circular-md': 'var(--sk-radius-circular-md)',
    'circular-sm': 'var(--sk-radius-circular-sm)',

    button: 'var(--sk-radius-button-DEFAULT)',
    'button-lg': 'var(--sk-radius-button-lg)',
    'button-md': 'var(--sk-radius-button-md)',
    'button-sm': 'var(--sk-radius-button-sm)',
    cards: 'var(--sk-radius-cards-DEFAULT)',
    'cards-lg': 'var(--sk-radius-cards-lg)',
    'cards-md': 'var(--sk-radius-cards-md)',
    'cards-sm': 'var(--sk-radius-cards-sm)',
    utility: 'var(--sk-radius-utility-DEFAULT)',
    'utility-lg': 'var(--sk-radius-utility-lg)',
    'utility-md': 'var(--sk-radius-utility-md)',
    'utility-sm': 'var(--sk-radius-utility-sm)',
    groups: 'var(--sk-radius-groups-DEFAULT)',
    'groups-lg': 'var(--sk-radius-groups-lg)',
    'groups-md': 'var(--sk-radius-groups-md)',
    'groups-sm': 'var(--sk-radius-groups-sm)',

    0: 'var(--sk-spacing-0)',
    2: 'var(--sk-spacing-2)',
    4: 'var(--sk-spacing-4)',
    6: 'var(--sk-spacing-6)',
    8: 'var(--sk-spacing-8)',
    10: 'var(--sk-spacing-10)',
    12: 'var(--sk-spacing-12)',
    14: 'var(--sk-spacing-14)',
    16: 'var(--sk-spacing-16)',
    18: 'var(--sk-spacing-18)',
    20: 'var(--sk-spacing-20)',
    24: 'var(--sk-spacing-24)',
    32: 'var(--sk-spacing-32)',
    40: 'var(--sk-spacing-40)',
    48: 'var(--sk-spacing-48)',
    56: 'var(--sk-spacing-56)',
    64: 'var(--sk-spacing-64)',
    72: 'var(--sk-spacing-72)',
    80: 'var(--sk-spacing-80)',
  },
};
