const _units = {
  spacing: {
    '0': 'var(--sk-spacing-0)',
    '0.25': 'var(--sk-spacing-0.25)',
    '0.5': 'var(--sk-spacing-0.5)',
    '0.75': 'var(--sk-spacing-0.75)',
    '1': 'var(--sk-spacing-1)',
    '2': 'var(--sk-spacing-2)',
    '3': 'var(--sk-spacing-3)',
    '4': 'var(--sk-spacing-4)',
    '5': 'var(--sk-spacing-5)',
    '6': 'var(--sk-spacing-6)',
    '7': 'var(--sk-spacing-7)',
    '8': 'var(--sk-spacing-8)',
    '9': 'var(--sk-spacing-9)',
    '10': 'var(--sk-spacing-10)',
    '11': 'var(--sk-spacing-11)',
    '12': 'var(--sk-spacing-12)',
    '13': 'var(--sk-spacing-13)',
    '14': 'var(--sk-spacing-14)',
    '15': 'var(--sk-spacing-15)',
    '16': 'var(--sk-spacing-16)',
    '17': 'var(--sk-spacing-17)',
    '18': 'var(--sk-spacing-18)',
    '19': 'var(--sk-spacing-19)',
    '20': 'var(--sk-spacing-20)',
    '22': 'var(--sk-spacing-22)',
    '24': 'var(--sk-spacing-24)',
    '26': 'var(--sk-spacing-26)',
    '28': 'var(--sk-spacing-28)',
    '30': 'var(--sk-spacing-30)',
    '32': 'var(--sk-spacing-32)',
    '34': 'var(--sk-spacing-34)',
    '36': 'var(--sk-spacing-36)',
    '38': 'var(--sk-spacing-38)',
    '40': 'var(--sk-spacing-40)',
    '42': 'var(--sk-spacing-42)',
    '44': 'var(--sk-spacing-44)',
    '46': 'var(--sk-spacing-46)',
    '48': 'var(--sk-spacing-48)',
    '50': 'var(--sk-spacing-50)',
    '52': 'var(--sk-spacing-52)',
    '54': 'var(--sk-spacing-54)',
    '56': 'var(--sk-spacing-56)',
    '58': 'var(--sk-spacing-58)',
    '60': 'var(--sk-spacing-60)',
    '62': 'var(--sk-spacing-62)',
    '64': 'var(--sk-spacing-64)',
    '68': 'var(--sk-spacing-68)',
    '72': 'var(--sk-spacing-72)',
    '80': 'var(--sk-spacing-80)',
    '90': 'var(--sk-spacing-90)',
    '100': 'var(--sk-spacing-100)',
  },

  fontSizes: {
    'display-1': [
      'var(--sk-fontSize-display-1-DEFAULT)',
      { lineHeight: 'var(--sk-lineHeight-display-1-DEFAULT)', fontWeight: 800 },
    ],
    'display-1-lg': [
      'var(--sk-fontSize-display-1-lg)',
      { lineHeight: 'var(--sk-lineHeight-display-1-lg)', fontWeight: 800 },
    ],
    'display-1-md': [
      'var(--sk-fontSize-display-1-md)',
      { lineHeight: 'var(--sk-lineHeight-display-1-md)', fontWeight: 800 },
    ],
    'display-1-sm': [
      'var(--sk-fontSize-display-1-sm)',
      { lineHeight: 'var(--sk-lineHeight-display-1-sm)', fontWeight: 800 },
    ],
    'display-2': [
      'var(--sk-fontSize-display-2-DEFAULT)',
      { lineHeight: 'var(--sk-lineHeight-display-2-DEFAULT)', fontWeight: 800 },
    ],
    'display-2-lg': [
      'var(--sk-fontSize-display-2-lg)',
      { lineHeight: 'var(--sk-lineHeight-display-2-lg)', fontWeight: 800 },
    ],
    'display-2-md': [
      'var(--sk-fontSize-display-2-md)',
      { lineHeight: 'var(--sk-lineHeight-display-2-md)', fontWeight: 800 },
    ],
    'display-2-sm': [
      'var(--sk-fontSize-display-2-sm)',
      { lineHeight: 'var(--sk-lineHeight-display-2-sm)', fontWeight: 800 },
    ],
    'display-3': [
      'var(--sk-fontSize-display-3-DEFAULT)',
      { lineHeight: 'var(--sk-lineHeight-display-3-DEFAULT)', fontWeight: 800 },
    ],
    'display-3-lg': [
      'var(--sk-fontSize-display-3-lg)',
      { lineHeight: 'var(--sk-lineHeight-display-3-lg)', fontWeight: 800 },
    ],
    'display-3-md': [
      'var(--sk-fontSize-display-3-md)',
      { lineHeight: 'var(--sk-lineHeight-display-3-md)', fontWeight: 800 },
    ],
    'display-3-sm': [
      'var(--sk-fontSize-display-3-sm)',
      { lineHeight: 'var(--sk-lineHeight-display-3-sm)', fontWeight: 800 },
    ],

    h1: ['var(--sk-fontSize-h-1-DEFAULT)', { lineHeight: 'var(--sk-lineHeight-h-1-DEFAULT)', fontWeight: 700 }],
    'h1-lg': ['var(--sk-fontSize-h-1-lg)', { lineHeight: 'var(--sk-lineHeight-h-1-lg)', fontWeight: 700 }],
    'h1-md': ['var(--sk-fontSize-h-1-md)', { lineHeight: 'var(--sk-lineHeight-h-1-md)', fontWeight: 700 }],
    'h1-sm': ['var(--sk-fontSize-h-1-sm)', { lineHeight: 'var(--sk-lineHeight-h-1-sm)', fontWeight: 700 }],
    h2: ['var(--sk-fontSize-h-2-DEFAULT)', { lineHeight: 'var(--sk-lineHeight-h-2-DEFAULT)', fontWeight: 700 }],
    'h2-lg': ['var(--sk-fontSize-h-2-lg)', { lineHeight: 'var(--sk-lineHeight-h-2-lg)', fontWeight: 700 }],
    'h2-md': ['var(--sk-fontSize-h-2-md)', { lineHeight: 'var(--sk-lineHeight-h-2-md)', fontWeight: 700 }],
    'h2-sm': ['var(--sk-fontSize-h-2-sm)', { lineHeight: 'var(--sk-lineHeight-h-2-sm)', fontWeight: 700 }],
    h3: ['var(--sk-fontSize-h-3-DEFAULT)', { lineHeight: 'var(--sk-lineHeight-h-3-DEFAULT)', fontWeight: 700 }],
    'h3-lg': ['var(--sk-fontSize-h-3-lg)', { lineHeight: 'var(--sk-lineHeight-h-3-lg)', fontWeight: 700 }],
    'h3-md': ['var(--sk-fontSize-h-3-md)', { lineHeight: 'var(--sk-lineHeight-h-3-md)', fontWeight: 700 }],
    'h3-sm': ['var(--sk-fontSize-h-3-sm)', { lineHeight: 'var(--sk-lineHeight-h-3-sm)', fontWeight: 700 }],
    h4: ['var(--sk-fontSize-h-4-DEFAULT)', { lineHeight: 'var(--sk-lineHeight-h-4-DEFAULT)', fontWeight: 700 }],
    'h4-lg': ['var(--sk-fontSize-h-4-lg)', { lineHeight: 'var(--sk-lineHeight-h-4-lg)', fontWeight: 700 }],
    'h4-md': ['var(--sk-fontSize-h-4-md)', { lineHeight: 'var(--sk-lineHeight-h-4-md)', fontWeight: 700 }],
    'h4-sm': ['var(--sk-fontSize-h-4-sm)', { lineHeight: 'var(--sk-lineHeight-h-4-sm)', fontWeight: 700 }],

    'label-large': [
      'var(--sk-fontSize-label-large)',
      { lineHeight: 'var(--sk-lineHeight-label-large)', fontWeight: 700 },
    ],
    'label-medium': [
      'var(--sk-fontSize-label-medium)',
      { lineHeight: 'var(--sk-lineHeight-label-medium)', fontWeight: 700 },
    ],
    'label-small': [
      'var(--sk-fontSize-label-small)',
      { lineHeight: 'var(--sk-lineHeight-label-small)', fontWeight: 700 },
    ],

    'input-large': [
      'var(--sk-fontSize-input-large)',
      { lineHeight: 'var(--sk-lineHeight-input-large)', fontWeight: 400 },
    ],
    'input-medium': [
      'var(--sk-fontSize-input-medium)',
      { lineHeight: 'var(--sk-lineHeight-input-medium)', fontWeight: 400 },
    ],
    'input-small': [
      'var(--sk-fontSize-input-small)',
      { lineHeight: 'var(--sk-lineHeight-input-small)', fontWeight: 400 },
    ],
    'logo-header': [
      'var(--sk-fontSize-logo-header)',
      { lineHeight: 'var(--sk-lineHeight-logo-header)', fontWeight: 700 },
    ],

    lead: ['var(--sk-fontSize-lead)', 'var(--sk-lineHeight-lead)'],
    base: ['var(--sk-fontSize-base)', 'var(--sk-lineHeight-base)'],
    large: ['var(--sk-fontSize-large)', 'var(--sk-lineHeight-large)'],
    small: ['var(--sk-fontSize-small)', 'var(--sk-lineHeight-small)'],
  },
  lineHeights: {
    'display-1': 'var(--sk-lineHeight-display-1-DEFAULT)',
    'display-1-lg': 'var(--sk-lineHeight-display-1-lg)',
    'display-1-md': 'var(--sk-lineHeight-display-1-md)',
    'display-1-sm': 'var(--sk-lineHeight-display-1-sm)',
    'display-2': 'var(--sk-lineHeight-display-2-DEFAULT)',
    'display-2-lg': 'var(--sk-lineHeight-display-2-lg)',
    'display-2-md': 'var(--sk-lineHeight-display-2-md)',
    'display-2-sm': 'var(--sk-lineHeight-display-2-sm)',
    'display-3': 'var(--sk-lineHeight-display-3-DEFAULT)',
    'display-3-lg': 'var(--sk-lineHeight-display-3-lg)',
    'display-3-md': 'var(--sk-lineHeight-display-3-md)',
    'display-3-sm': 'var(--sk-lineHeight-display-3-sm)',

    h1: 'var(--sk-lineHeight-h-1-DEFAULT)',
    'h1-lg': 'var(--sk-lineHeight-h-1-lg)',
    'h1-md': 'var(--sk-lineHeight-h-1-md)',
    'h1-sm': 'var(--sk-lineHeight-h-1-sm)',
    h2: 'var(--sk-lineHeight-h-2-DEFAULT)',
    'h2-lg': 'var(--sk-lineHeight-h-2-lg)',
    'h2-md': 'var(--sk-lineHeight-h-2-md)',
    'h2-sm': 'var(--sk-lineHeight-h-2-sm)',
    h3: 'var(--sk-lineHeight-h-3-DEFAULT)',
    'h3-lg': 'var(--sk-lineHeight-h-3-lg)',
    'h3-md': 'var(--sk-lineHeight-h-3-md)',
    'h3-sm': 'var(--sk-lineHeight-h-3-sm)',
    h4: 'var(--sk-lineHeight-h-4-DEFAULT)',
    'h4-lg': 'var(--sk-lineHeight-h-4-lg)',
    'h4-md': 'var(--sk-lineHeight-h-4-md)',
    'h4-sm': 'var(--sk-lineHeight-h-4-sm)',

    'label-large': 'var(--sk-lineHeight-label-large)',
    'label-medium': 'var(--sk-lineHeight-label-medium)',
    'label-small': 'var(--sk-lineHeight-label-small)',

    'input-large': 'var(--sk-lineHeight-input-large)',
    'input-medium': 'var(--sk-lineHeight-input-medium)',
    'input-small': 'var(--sk-lineHeight-input-small)',
    'logo-header': 'var(--sk-lineHeight-logo-header)',
    lead: 'var(--sk-lineHeight-lead)',
    base: 'var(--sk-lineHeight-base)',
    large: 'var(--sk-lineHeight-large)',
    small: 'var(--sk-lineHeight-small)',
  },
  radius: {
    DEFAULT: 'var(--sk-radius-utility-DEFAULT)',
    full: 'var(--sk-radius-circular-DEFAULT)',
    none: 'var(--sk-spacing-0)',
    circular: 'var(--sk-radius-circular-DEFAULT)',
    'circular-lg': 'var(--sk-radius-circular-lg)',
    'circular-md': 'var(--sk-radius-circular-md)',
    'circular-sm': 'var(--sk-radius-circular-sm)',

    button: 'var(--sk-radius-button-DEFAULT)',
    'button-lg': 'var(--sk-radius-button-lg)',
    'button-md': 'var(--sk-radius-button-md)',
    'button-sm': 'var(--sk-radius-button-sm)',
    cards: 'var(--sk-radius-cards-DEFAULT)',
    'cards-lg': 'var(--sk-radius-cards-lg)',
    'cards-md': 'var(--sk-radius-cards-md)',
    'cards-sm': 'var(--sk-radius-cards-sm)',
    utility: 'var(--sk-radius-utility-DEFAULT)',
    'utility-lg': 'var(--sk-radius-utility-lg)',
    'utility-md': 'var(--sk-radius-utility-md)',
    'utility-sm': 'var(--sk-radius-utility-sm)',
    groups: 'var(--sk-radius-groups-DEFAULT)',
    'groups-lg': 'var(--sk-radius-groups-lg)',
    'groups-md': 'var(--sk-radius-groups-md)',
    'groups-sm': 'var(--sk-radius-groups-sm)',

    '0': 'var(--sk-spacing-0)',
    '2': 'var(--sk-spacing-2)',
    '4': 'var(--sk-spacing-4)',
    '6': 'var(--sk-spacing-6)',
    '8': 'var(--sk-spacing-8)',
    '10': 'var(--sk-spacing-10)',
    '12': 'var(--sk-spacing-12)',
    '14': 'var(--sk-spacing-14)',
    '16': 'var(--sk-spacing-16)',
    '18': 'var(--sk-spacing-18)',
    '20': 'var(--sk-spacing-20)',
    '24': 'var(--sk-spacing-24)',
    '32': 'var(--sk-spacing-32)',
    '40': 'var(--sk-spacing-40)',
    '48': 'var(--sk-spacing-48)',
    '56': 'var(--sk-spacing-56)',
    '64': 'var(--sk-spacing-64)',
    '72': 'var(--sk-spacing-72)',
    '80': 'var(--sk-spacing-80)',
  },
};
const units: typeof _units = _units;
export { units };
