export const spacing = {
  0: '0px',
  '0.25': '0.025rem',
  '0.5': '0.05rem',
  '0.75': '0.075rem',
  1: '0.1rem',
  2: '0.2rem',
  3: '0.3rem',
  4: '0.4rem',
  5: '0.5rem',
  6: '0.6rem',
  7: '0.7rem',
  8: '0.8rem',
  9: '0.9rem',
  10: '1rem',
  11: '1.1rem',
  12: '1.2rem',
  13: '1.3rem',
  14: '1.4rem',
  15: '1.5rem',
  16: '1.6rem',
  17: '1.7rem',
  18: '1.8rem',
  19: '1.9rem',
  20: '2rem',
  22: '2.2rem',
  24: '2.4rem',
  26: '2.6rem',
  28: '2.8rem',
  30: '3rem',
  32: '3.2rem',
  34: '3.4rem',
  36: '3.6rem',
  38: '3.8rem',
  40: '4rem',
  42: '4.2rem',
  44: '4.4rem',
  46: '4.6rem',
  48: '4.8rem',
  50: '5rem',
  52: '5.2rem',
  54: '5.4rem',
  56: '5.6rem',
  58: '5.8rem',
  60: '6rem',
  62: '6.2rem',
  64: '6.4rem',
  68: '6.8rem',
  72: '7.2rem',
  80: '8rem',
  90: '9rem',
  100: '10rem',
};

export const breakpoints = {
  phone: {
    DEFAULT: '320px',
    min: '320px',
    max: '479px',
  },
  'small-device': {
    DEFAULT: '480px',
    min: '480px',
    max: '767px',
  },
  'medium-device': {
    DEFAULT: '768px',
    min: '768px',
    max: '1023px',
  },
  'large-device': {
    DEFAULT: '1024px',
    min: '1024px',
    max: '1365px',
  },
  desktop: {
    DEFAULT: '1366px',
    min: '1366px',
    max: '1600px',
  },
};

export const screens = {
  xs: breakpoints.phone.DEFAULT,
  sm: breakpoints['small-device'].DEFAULT,
  md: breakpoints['medium-device'].DEFAULT,
  lg: breakpoints['large-device'].DEFAULT,
  xl: breakpoints.desktop.DEFAULT,
  phone: breakpoints.phone.DEFAULT,
  'phone-min': breakpoints.phone.min,
  'phone-max': breakpoints.phone.max,
  'small-device': breakpoints['small-device'].DEFAULT,
  'small-device-min': breakpoints['small-device'].min,
  'small-device-max': breakpoints['small-device'].max,
  'medium-device': breakpoints['medium-device'].DEFAULT,
  'medium-device-min': breakpoints['medium-device'].min,
  'medium-device-max': breakpoints['medium-device'].max,
  'large-device': breakpoints['large-device'].DEFAULT,
  'large-device-min': breakpoints['large-device'].min,
  'large-device-max': breakpoints['large-device'].max,
  desktop: breakpoints.desktop.DEFAULT,
  'desktop-min': breakpoints.desktop.min,
  'desktop-max': breakpoints.desktop.max,
};

export const fontSizes = {
  display: {
    1: {
      DEFAULT: '8rem',
      lg: '8rem',
      md: '7.2rem',
      sm: '5.6rem',
    },
    2: {
      DEFAULT: '6.4rem',
      lg: '6.4rem',
      md: '5.6rem',
      sm: '4.4rem',
    },
    3: {
      DEFAULT: '4.8rem',
      lg: '4.8rem',
      md: '4rem',
      sm: '3.2rem',
    },
  },
  h: {
    1: {
      DEFAULT: '4rem',
      lg: '4rem',
      md: '3.4rem',
      sm: '3.2rem',
    },
    2: {
      DEFAULT: '3.2rem',
      lg: '3.2rem',
      md: '2.8rem',
      sm: '2.6rem',
    },
    3: {
      DEFAULT: '2.6rem',
      lg: '2.6rem',
      md: '2.2rem',
      sm: '2rem',
    },
    4: {
      DEFAULT: '2.4rem',
      lg: '2.4rem',
      md: '2rem',
      sm: '1.8rem',
    },
  },
  label: {
    large: '1.8rem',
    medium: '1.6rem',
    small: '1.4rem',
    'extra-small': '1.2rem'
  },
  input: {
    large: '1.8rem',
    medium: '1.6rem',
    small: '1.4rem',
  },
  logo: {
    header: '2.2rem',
  },
  lead: '2rem',
  base: '1.6rem',
  large: '1.8rem',
  small: '1.4rem',
};

export const lineHeights = {
  display: {
    1: {
      DEFAULT: '9.6rem',
      lg: '9.6rem',
      md: '8rem',
      sm: '6.4rem',
    },
    2: {
      DEFAULT: '7.2rem',
      lg: '7.2rem',
      md: '6.4rem',
      sm: '5.6rem',
    },
    3: {
      DEFAULT: '5.6rem',
      lg: '5.6rem',
      md: '4.8rem',
      sm: '3.6rem',
    },
  },
  h: {
    1: {
      DEFAULT: '5.6rem',
      lg: '5.6rem',
      md: '4.8rem',
      sm: '4.4rem',
    },
    2: {
      DEFAULT: '4rem',
      lg: '4rem',
      md: '3.6rem',
      sm: '3.2rem',
    },
    3: {
      DEFAULT: '3.4rem',
      lg: '3.4rem',
      md: '3rem',
      sm: '2.8rem',
    },
    4: {
      DEFAULT: '3.2rem',
      lg: '3.2rem',
      md: '2.8rem',
      sm: '2.4rem',
    },
  },
  label: {
    large: '3.2rem',
    medium: '2.4rem',
    small: '1.6rem',
    'extra-small': '1.8rem',
  },
  input: {
    large: '2.4rem',
    medium: '2.4rem',
    small: '2rem',
  },
  logo: {
    header: '2.8rem',
  },
  lead: '2.8rem',
  base: '2.4rem',
  large: '2.6rem',
  small: '1.8rem',
};

export const radius = {
  circular: {
    DEFAULT: '1000000rem',
    lg: '1000000rem',
    md: '1000000rem',
    sm: '1000000rem',
  },
  button: {
    DEFAULT: spacing[12],
    lg: spacing[12],
    md: spacing[12],
    sm: spacing[10],
  },
  cards: {
    DEFAULT: spacing[20],
    lg: spacing[20],
    md: spacing[20],
    sm: spacing[20],
  },
  utility: {
    DEFAULT: spacing[8],
    lg: spacing[8],
    md: spacing[8],
    sm: spacing[8],
  },
  groups: {
    DEFAULT: spacing[16],
    lg: spacing[16],
    md: spacing[16],
    sm: spacing[16],
  },
};
