export interface CountryCode {
  name: string;
  flag: string;
  countryCode: number;
  isoCode: string;
}
export const countryCodes: CountryCode[] = [
  { name: 'United States', flag: '🇺🇸', countryCode: 1, isoCode: 'US' },
  { name: 'United States Virgin Islands', flag: '🇻🇬', countryCode: 340, isoCode: 'VI' },
  { name: 'Northern Mariana Islands', flag: '🇲🇵', countryCode: 670, isoCode: 'MP' },
  { name: 'Guam', flag: '🇬🇺', countryCode: 671, isoCode: 'GU' },
  { name: 'American Samoa', flag: '🇦🇸', countryCode: 684, isoCode: 'AS' },
  { name: 'Puerto Rico', flag: '🇵🇷', countryCode: 787, isoCode: 'PR' },
  { name: 'Canada', flag: '🇨🇦', countryCode: 1, isoCode: 'CA' },
  { name: 'Bahamas', flag: '🇧🇸', countryCode: 242, isoCode: 'BS' },
  { name: 'Barbados', flag: '🇧🇧', countryCode: 246, isoCode: 'BB' },
  { name: 'Anguilla', flag: '🇦🇮', countryCode: 264, isoCode: 'AI' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', countryCode: 268, isoCode: 'AG' },
  { name: 'British Virgin Islands', flag: '🇻🇬', countryCode: 284, isoCode: 'VG' },
  { name: 'Cayman Islands', flag: '🇰🇾', countryCode: 345, isoCode: 'KY' },
  { name: 'Bermuda', flag: '🇧🇲', countryCode: 441, isoCode: 'BM' },
  { name: 'Grenada', flag: '🇬🇩', countryCode: 473, isoCode: 'GD' },
  { name: 'Turks and Caicos Islands', flag: '🇹🇨', countryCode: 649, isoCode: 'TC' },
  { name: 'Jamaica', flag: '🇯🇲', countryCode: 658, isoCode: 'JM' },
  { name: 'Montserrat', flag: '🇲🇰', countryCode: 664, isoCode: 'MS' },
  { name: 'Sint Maarten', flag: '🇸🇽', countryCode: 721, isoCode: 'SX' },
  { name: 'Saint Lucia', flag: '🇱🇨', countryCode: 758, isoCode: 'LC' },
  { name: 'Dominica', flag: '🇩🇲', countryCode: 767, isoCode: 'DM' },
  { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', countryCode: 784, isoCode: 'VC' },
  { name: 'Dominican Republic', flag: '🇩🇴', countryCode: 809, isoCode: 'DO' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', countryCode: 868, isoCode: 'TT' },
  { name: 'Saint Kitts and Nevis', flag: '🇰🇳', countryCode: 869, isoCode: 'KN' },
  { name: 'Egypt', flag: '🇪🇬', countryCode: 20, isoCode: 'EG' },
  { name: 'South Sudan', flag: '🇸🇩', countryCode: 211, isoCode: 'SS' },
  { name: 'Morocco', flag: '🇲🇦', countryCode: 212, isoCode: 'MA' },
  { name: 'Algeria', flag: '🇩🇿', countryCode: 213, isoCode: 'DZ' },
  { name: 'Tunisia', flag: '🇹🇳', countryCode: 216, isoCode: 'TN' },
  { name: 'Libya', flag: '🇱🇾', countryCode: 218, isoCode: 'LY' },
  { name: 'Gambia', flag: '🇬🇲', countryCode: 220, isoCode: 'GM' },
  { name: 'Senegal', flag: '🇸🇳', countryCode: 221, isoCode: 'SN' },
  { name: 'Mauritania', flag: '🇲🇷', countryCode: 222, isoCode: 'MR' },
  { name: 'Mali', flag: '🇲🇱', countryCode: 223, isoCode: 'ML' },
  { name: 'Guinea', flag: '🇬🇳', countryCode: 224, isoCode: 'GN' },
  { name: 'Ivory Coast', flag: '🇨🇮', countryCode: 225, isoCode: 'CI' },
  { name: 'Burkina Faso', flag: '🇧🇫', countryCode: 226, isoCode: 'BF' },
  { name: 'Niger', flag: '🇳🇪', countryCode: 227, isoCode: 'NE' },
  { name: 'Togo', flag: '🇹🇬', countryCode: 228, isoCode: 'TG' },
  { name: 'Benin', flag: '🇧🇯', countryCode: 229, isoCode: 'BJ' },
  { name: 'Mauritius', flag: '🇲🇺', countryCode: 230, isoCode: 'MU' },
  { name: 'Liberia', flag: '🇱🇷', countryCode: 231, isoCode: 'LR' },
  { name: 'Sierra Leone', flag: '🇸🇱', countryCode: 232, isoCode: 'SL' },
  { name: 'Ghana', flag: '🇬🇭', countryCode: 233, isoCode: 'GH' },
  { name: 'Nigeria', flag: '🇳🇬', countryCode: 234, isoCode: 'NG' },
  { name: 'Chad', flag: '🇹🇩', countryCode: 235, isoCode: 'TD' },
  { name: 'Central African Republic', flag: '🇨🇫', countryCode: 236, isoCode: 'CF' },
  { name: 'Cameroon', flag: '🇨🇲', countryCode: 237, isoCode: 'CM' },
  { name: 'Cape Verde', flag: '🇨🇻', countryCode: 238, isoCode: 'CV' },
  { name: 'São Tomé and Príncipe', flag: '🇸🇹', countryCode: 239, isoCode: 'ST' },
  { name: 'Equatorial Guinea', flag: '🇬🇶', countryCode: 240, isoCode: 'GQ' },
  { name: 'Gabon', flag: '🇬🇦', countryCode: 241, isoCode: 'GA' },
  { name: 'Republic of the Congo', flag: '🇨🇬', countryCode: 242, isoCode: 'CG' },
  { name: 'Democratic Republic of the Congo', flag: '🇨🇩', countryCode: 243, isoCode: 'CD' },
  { name: 'Angola', flag: '🇦🇴', countryCode: 244, isoCode: 'AO' },
  { name: 'Guinea-Bissau', flag: '🇬🇼', countryCode: 245, isoCode: 'GW' },
  { name: 'British Indian Ocean Territory', flag: '🕌', countryCode: 246, isoCode: 'IO' },
  { name: 'Ascension Island', flag: '🇦🇨', countryCode: 247, isoCode: 'AC' },
  { name: 'Seychelles', flag: '🇸🇨', countryCode: 248, isoCode: 'SC' },
  { name: 'Sudan', flag: '🇸🇩', countryCode: 249, isoCode: 'SD' },
  { name: 'Rwanda', flag: '🇷🇼', countryCode: 250, isoCode: 'RW' },
  { name: 'Ethiopia', flag: '🇪🇹', countryCode: 251, isoCode: 'ET' },
  { name: 'Somalia', flag: '🇸🇴', countryCode: 252, isoCode: 'SO' },
  { name: 'Djibouti', flag: '🇩🇯', countryCode: 253, isoCode: 'DJ' },
  { name: 'Kenya', flag: '🇰🇪', countryCode: 254, isoCode: 'KE' },
  { name: 'Tanzania', flag: '🇹🇿', countryCode: 255, isoCode: 'TZ' },
  { name: 'Uganda', flag: '🇺🇬', countryCode: 256, isoCode: 'UG' },
  { name: 'Burundi', flag: '🇧🇮', countryCode: 257, isoCode: 'BI' },
  { name: 'Mozambique', flag: '🇲🇿', countryCode: 258, isoCode: 'MZ' },
  { name: 'Zambia', flag: '🇿🇲', countryCode: 260, isoCode: 'ZM' },
  { name: 'Madagascar', flag: '🇲🇬', countryCode: 261, isoCode: 'MG' },
  { name: 'Réunion', flag: '🇷🇪', countryCode: 262, isoCode: 'RE' },
  { name: 'Mayotte', flag: '🇾🇹', countryCode: 262, isoCode: 'YT' },
  { name: 'Zimbabwe', flag: '🇿🇼', countryCode: 263, isoCode: 'ZW' },
  { name: 'Namibia', flag: '🇳🇦', countryCode: 264, isoCode: 'NA' },
  { name: 'Malawi', flag: '🇲🇼', countryCode: 265, isoCode: 'MW' },
  { name: 'Lesotho', flag: '🇱🇸', countryCode: 266, isoCode: 'LS' },
  { name: 'Botswana', flag: '🇧🇼', countryCode: 267, isoCode: 'BW' },
  { name: 'Eswatini', flag: '🇸🇿', countryCode: 268, isoCode: 'SZ' },
  { name: 'Comoros', flag: '🇰🇲', countryCode: 269, isoCode: 'KM' },
  { name: 'South Africa', flag: '🇿🇦', countryCode: 27, isoCode: 'ZA' },
  { name: 'Saint Helena', flag: '🇸🇭', countryCode: 290, isoCode: 'SH' },
  { name: 'Tristan da Cunha', flag: '🇹🇷', countryCode: 290, isoCode: 'TA' },
  { name: 'Eritrea', flag: '🇪🇷', countryCode: 291, isoCode: 'ER' },
  { name: 'Aruba', flag: '🇦🇼', countryCode: 297, isoCode: 'AW' },
  { name: 'Faroe Islands', flag: '🇫🇴', countryCode: 298, isoCode: 'FO' },
  { name: 'Greenland', flag: '🇬🇱', countryCode: 299, isoCode: 'GL' },
  { name: 'Greece', flag: '🇬🇷', countryCode: 30, isoCode: 'GR' },
  { name: 'Netherlands', flag: '🇳🇱', countryCode: 31, isoCode: 'NL' },
  { name: 'Belgium', flag: '🇧🇪', countryCode: 32, isoCode: 'BE' },
  { name: 'France', flag: '🇫🇷', countryCode: 33, isoCode: 'FR' },
  { name: 'Spain', flag: '🇪🇸', countryCode: 34, isoCode: 'ES' },
  { name: 'Gibraltar', flag: '🇬🇮', countryCode: 350, isoCode: 'GI' },
  { name: 'Portugal', flag: '🇵🇹', countryCode: 351, isoCode: 'PT' },
  { name: 'Luxembourg', flag: '🇱🇺', countryCode: 352, isoCode: 'LU' },
  { name: 'Ireland', flag: '🇮🇪', countryCode: 353, isoCode: 'IE' },
  { name: 'Iceland', flag: '🇮🇸', countryCode: 354, isoCode: 'IS' },
  { name: 'Albania', flag: '🇦🇱', countryCode: 355, isoCode: 'AL' },
  { name: 'Malta', flag: '🇲🇹', countryCode: 356, isoCode: 'MT' },
  { name: 'Cyprus', flag: '🇨🇾', countryCode: 357, isoCode: 'CY' },
  { name: 'Finland', flag: '🇫🇮', countryCode: 358, isoCode: 'FI' },
  { name: 'Åland', flag: '🇦🇽', countryCode: 358, isoCode: 'AX' },
  { name: 'Bulgaria', flag: '🇧🇬', countryCode: 359, isoCode: 'BG' },
  { name: 'Hungary', flag: '🇭🇺', countryCode: 36, isoCode: 'HU' },
  { name: 'Lithuania', flag: '🇱🇹', countryCode: 370, isoCode: 'LT' },
  { name: 'Latvia', flag: '🇱🇻', countryCode: 371, isoCode: 'LV' },
  { name: 'Estonia', flag: '🇪🇪', countryCode: 372, isoCode: 'EE' },
  { name: 'Moldova', flag: '🇲🇩', countryCode: 373, isoCode: 'MD' },
  { name: 'Armenia', flag: '🇦🇲', countryCode: 374, isoCode: 'AM' },
  { name: 'Belarus', flag: '🇧🇾', countryCode: 375, isoCode: 'BY' },
  { name: 'Andorra', flag: '🇦🇩', countryCode: 376, isoCode: 'AD' },
  { name: 'Monaco', flag: '🇲🇨', countryCode: 377, isoCode: 'MC' },
  { name: 'San Marino', flag: '🇸🇲', countryCode: 378, isoCode: 'SM' },
  { name: 'Vatican City', flag: '🇻🇦', countryCode: 379, isoCode: 'VA' },
  { name: 'Ukraine', flag: '🇺🇦', countryCode: 380, isoCode: 'UA' },
  { name: 'Serbia', flag: '🇷🇸', countryCode: 381, isoCode: 'RS' },
  { name: 'Montenegro', flag: '🇲🇪', countryCode: 382, isoCode: 'ME' },
  { name: 'Kosovo', flag: '🇽🇰', countryCode: 383, isoCode: ' XK' },
  { name: 'Croatia', flag: '🇭🇷', countryCode: 385, isoCode: 'HR' },
  { name: 'Slovenia', flag: '🇸🇮', countryCode: 386, isoCode: 'SI' },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', countryCode: 387, isoCode: 'BA' },
  { name: 'North Macedonia', flag: '🇲🇰', countryCode: 389, isoCode: 'MK' },
  { name: 'Italy', flag: '🇮🇹', countryCode: 39, isoCode: 'IT' },
  { name: 'Romania', flag: '🇷🇴', countryCode: 40, isoCode: 'RO' },
  { name: 'Switzerland', flag: '🇨🇭', countryCode: 41, isoCode: 'CH' },
  { name: 'Czech Republic', flag: '🇨🇿', countryCode: 420, isoCode: 'CZ' },
  { name: 'Slovakia', flag: '🇸🇰', countryCode: 421, isoCode: 'SK' },
  { name: 'Liechtenstein', flag: '🇱🇮', countryCode: 423, isoCode: 'LI' },
  { name: 'Austria', flag: '🇦🇹', countryCode: 43, isoCode: 'AT' },
  { name: 'United Kingdom', flag: '🇬🇧', countryCode: 44, isoCode: 'GB' },
  { name: 'Denmark', flag: '🇩🇰', countryCode: 45, isoCode: 'DK' },
  { name: 'Sweden', flag: '🇸🇪', countryCode: 46, isoCode: 'SE' },
  { name: 'Norway', flag: '🇳🇴', countryCode: 47, isoCode: 'NO' },
  { name: 'Poland', flag: '🇵🇱', countryCode: 48, isoCode: 'PL' },
  { name: 'Germany', flag: '🇩🇪', countryCode: 49, isoCode: 'DE' },
  { name: 'Falkland Islands', flag: '🇫🇰', countryCode: 500, isoCode: 'FK' },
  { name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸', countryCode: 500, isoCode: 'GS' },
  { name: 'Belize', flag: '🇧🇿', countryCode: 501, isoCode: 'BZ' },
  { name: 'Guatemala', flag: '🇬🇹', countryCode: 502, isoCode: 'GT' },
  { name: 'El Salvador', flag: '🇸🇻', countryCode: 503, isoCode: 'SV' },
  { name: 'Honduras', flag: '🇭🇳', countryCode: 504, isoCode: 'HN' },
  { name: 'Nicaragua', flag: '🇳🇮', countryCode: 505, isoCode: 'NI' },
  { name: 'Costa Rica', flag: '🇨🇷', countryCode: 506, isoCode: 'CR' },
  { name: 'Panama', flag: '🇵🇦', countryCode: 507, isoCode: 'PA' },
  { name: 'Saint-Pierre and Miquelon', flag: '🇵🇲', countryCode: 508, isoCode: 'PM' },
  { name: 'Haiti', flag: '🇭🇹', countryCode: 509, isoCode: 'HT' },
  { name: 'Peru', flag: '🇵🇪', countryCode: 51, isoCode: 'PE' },
  { name: 'Mexico', flag: '🇲🇽', countryCode: 52, isoCode: 'MX' },
  { name: 'Cuba', flag: '🇨🇺', countryCode: 53, isoCode: 'CU' },
  { name: 'Argentina', flag: '🇦🇷', countryCode: 54, isoCode: 'AR' },
  { name: 'Brazil', flag: '🇧🇷', countryCode: 55, isoCode: 'BR' },
  { name: 'Chile', flag: '🇨🇱', countryCode: 56, isoCode: 'CL' },
  { name: 'Colombia', flag: '🇨🇴', countryCode: 57, isoCode: 'CO' },
  { name: 'Venezuela', flag: '🇻🇪', countryCode: 58, isoCode: 'VE' },
  { name: 'Guadeloupe', flag: '🇬🇵', countryCode: 590, isoCode: 'GP' },
  { name: 'Bolivia', flag: '🇧🇴', countryCode: 591, isoCode: 'BO' },
  { name: 'Guyana', flag: '🇬🇾', countryCode: 592, isoCode: 'GY' },
  { name: 'Ecuador', flag: '🇪🇨', countryCode: 593, isoCode: 'EC' },
  { name: 'French Guiana', flag: '🇬🇫', countryCode: 594, isoCode: 'GF' },
  { name: 'Paraguay', flag: '🇵🇾', countryCode: 595, isoCode: 'PY' },
  { name: 'Martinique', flag: '🇲🇶', countryCode: 596, isoCode: 'MQ' },
  { name: 'Suriname', flag: '🇸🇷', countryCode: 597, isoCode: 'SR' },
  { name: 'Uruguay', flag: '🇺🇾', countryCode: 598, isoCode: 'UY' },
  { name: 'Sint Eustatius / Saba / Bonaire', flag: '🇸🇷', countryCode: 599, isoCode: 'BQ' },
  { name: 'Curaçao', flag: '🇭🇺', countryCode: 599, isoCode: 'CW' },
  { name: 'Malaysia', flag: '🇲🇾', countryCode: 60, isoCode: 'MY' },
  { name: 'Australia', flag: '🇦🇺', countryCode: 61, isoCode: 'AU' },
  { name: 'Indonesia', flag: '🇮🇩', countryCode: 62, isoCode: 'ID' },
  { name: 'Philippines', flag: '🇵🇭', countryCode: 63, isoCode: 'PH' },
  { name: 'New Zealand', flag: '🇳🇿', countryCode: 64, isoCode: 'NZ' },
  { name: 'Singapore', flag: '🇸🇬', countryCode: 65, isoCode: 'SG' },
  { name: 'Thailand', flag: '🇹🇭', countryCode: 66, isoCode: 'TH' },
  { name: 'East Timor', flag: '🇹🇱', countryCode: 670, isoCode: 'TL' },
  { name: 'Brunei', flag: '🇧🇳', countryCode: 673, isoCode: 'BN' },
  { name: 'Nauru', flag: '🇳🇷', countryCode: 674, isoCode: 'NR' },
  { name: 'Papua New Guinea', flag: '🇵🇬', countryCode: 675, isoCode: 'PG' },
  { name: 'Tonga', flag: '🇹🇴', countryCode: 676, isoCode: 'TO' },
  { name: 'Solomon Islands', flag: '🇸🇧', countryCode: 677, isoCode: 'SB' },
  { name: 'Vanuatu', flag: '🇻🇺', countryCode: 678, isoCode: 'VU' },
  { name: 'Fiji', flag: '🇫🇯', countryCode: 679, isoCode: 'FJ' },
  { name: 'Palau', flag: '🇵🇼', countryCode: 680, isoCode: 'PW' },
  { name: 'Wallis and Futuna', flag: '🇼🇫', countryCode: 681, isoCode: 'WF' },
  { name: 'Cook Islands', flag: '🇨🇰', countryCode: 682, isoCode: 'CK' },
  { name: 'Niue', flag: '🇳🇺', countryCode: 683, isoCode: 'NU' },
  { name: 'Samoa', flag: '🇼🇸', countryCode: 685, isoCode: 'WS' },
  { name: 'Kiribati', flag: '🇰🇷', countryCode: 686, isoCode: 'KI' },
  { name: 'New Caledonia', flag: '🇳🇨', countryCode: 687, isoCode: 'NC' },
  { name: 'Tuvalu', flag: '🇹🇻', countryCode: 688, isoCode: 'TV' },
  { name: 'French Polynesia', flag: '🇵🇫', countryCode: 689, isoCode: 'PF' },
  { name: 'Tokelau', flag: '🇹🇰', countryCode: 690, isoCode: 'TK' },
  { name: 'Federated States of Micronesia', flag: '🇫🇲', countryCode: 691, isoCode: 'FM' },
  { name: 'Marshall Islands', flag: '🇲🇭', countryCode: 692, isoCode: 'MH' },
  { name: 'Russia', flag: '🇷🇺', countryCode: 7, isoCode: 'RU' },
  { name: 'Abkhazia', flag: '🇦🇿', countryCode: 840, isoCode: 'GE' },
  { name: 'South Ossetia', flag: '🇩🇿', countryCode: 850, isoCode: 'GE' },
  { name: 'Kazakhstan', flag: '🇰🇿', countryCode: 7, isoCode: 'KZ' },
  { name: 'Japan', flag: '🇯🇵', countryCode: 81, isoCode: 'JP' },
  { name: 'South Korea', flag: '🇰🇷', countryCode: 82, isoCode: 'KR' },
  { name: 'Vietnam', flag: '🇻🇳', countryCode: 84, isoCode: 'VN' },
  { name: 'North Korea', flag: '🇰🇵', countryCode: 850, isoCode: 'KP' },
  { name: 'Hong Kong', flag: '🇭🇰', countryCode: 852, isoCode: 'HK' },
  { name: 'Macau', flag: '🇲🇴', countryCode: 853, isoCode: 'MO' },
  { name: 'Cambodia', flag: '🇰🇭', countryCode: 855, isoCode: 'KH' },
  { name: 'Laos', flag: '🇱🇦', countryCode: 856, isoCode: 'LA' },
  { name: 'China', flag: '🇨🇳', countryCode: 86, isoCode: 'CN' },
  { name: 'Turkey', flag: '🇹🇷', countryCode: 90, isoCode: 'TR' },
  { name: 'Northern Cyprus', flag: '🇹🇷', countryCode: 90, isoCode: 'CY' },
  { name: 'India', flag: '🇮🇳', countryCode: 91, isoCode: 'IN' },
  { name: 'Pakistan', flag: '🇵🇰', countryCode: 92, isoCode: 'PK' },
  { name: 'Afghanistan', flag: '🇦🇫', countryCode: 93, isoCode: 'AF' },
  { name: 'Sri Lanka', flag: '🇱🇰', countryCode: 94, isoCode: 'LK' },
  { name: 'Myanmar', flag: '🇲🇲', countryCode: 95, isoCode: 'MM' },
  { name: 'Maldives', flag: '🇲🇻', countryCode: 960, isoCode: 'MV' },
  { name: 'Lebanon', flag: '🇱🇧', countryCode: 961, isoCode: 'LB' },
  { name: 'Jordan', flag: '🇯🇴', countryCode: 962, isoCode: 'JO' },
  { name: 'Syria', flag: '🇸🇾', countryCode: 963, isoCode: 'SY' },
  { name: 'Iraq', flag: '🇮🇶', countryCode: 964, isoCode: 'IQ' },
  { name: 'Kuwait', flag: '🇰🇼', countryCode: 965, isoCode: 'KW' },
  { name: 'Saudi Arabia', flag: '🇸🇦', countryCode: 966, isoCode: 'SA' },
  { name: 'Yemen', flag: '🇾🇪', countryCode: 967, isoCode: 'YE' },
  { name: 'Oman', flag: '🇴🇲', countryCode: 968, isoCode: 'OM' },
  { name: 'Palestine', flag: '🇵🇸', countryCode: 970, isoCode: 'PS' },
  { name: 'United Arab Emirates', flag: '🇦🇪', countryCode: 971, isoCode: 'AE' },
  { name: 'Israel', flag: '🇮🇱', countryCode: 972, isoCode: 'IL' },
  { name: 'Bahrain', flag: '🇧🇭', countryCode: 973, isoCode: 'BH' },
  { name: 'Qatar', flag: '🇶🇦', countryCode: 974, isoCode: 'QA' },
  { name: 'Bhutan', flag: '🇧🇹', countryCode: 975, isoCode: 'BT' },
  { name: 'Mongolia', flag: '🇲🇳', countryCode: 976, isoCode: 'MN' },
  { name: 'Nepal', flag: '🇳🇵', countryCode: 977, isoCode: 'NP' },
  { name: 'Iran', flag: '🇮🇷', countryCode: 98, isoCode: 'IR' },
  { name: 'Tajikistan', flag: '🇹🇯', countryCode: 992, isoCode: 'TJ' },
  { name: 'Turkmenistan', flag: '🇹🇲', countryCode: 993, isoCode: 'TM' },
  { name: 'Azerbaijan', flag: '🇦🇿', countryCode: 994, isoCode: 'AZ' },
  { name: 'Georgia', flag: '🇬🇪', countryCode: 995, isoCode: 'GE' },
  { name: 'Kyrgyzstan', flag: '🇰🇬', countryCode: 996, isoCode: 'KG' },
  { name: 'Uzbekistan', flag: '🇺🇿', countryCode: 998, isoCode: 'UZ' },
];
